spring:
  #kafka相关配置
  kafka:
    bootstrap-servers: localhost:9092
  #邮件相关配置
  mail:
    #邮件推送
    enabled: true
    host: smtp.qq.com
    port: 465
    username: xxx@foxmail.com
    password: sgowrdnbvoefbhjd
    default-encoding: UTF-8
    protocol: smtps

msg:
  #采用哪种MQ，可选择[eventBus]、[kafka]，不配置时默认采用eventBus
  mq-type: eventBus

  #其他配置
  max-sms-per-second: 10 #每秒钟发送短信条数上限

  #App消息推送(只能选择启用一种)
  jpush:
    enabled: true
    appKey: dsfdsafs
    master-secret: sdfsa
  getui:
    enabled: false
    appId: 2475897384
    url: http://example.com
    master-secret: zxlfsj
    appKey: 8099789

  #短信推送(只能选择启用一种)
  qcloud:
    enabled: true
    appId: 1114234
    appKey: sdfjs
  aliyun:
    enabled: false
    region: cn-chengdu
    access-key: abcdjsad
    access-secret: fdasjfkl
  yunpian:
    enabled: false
    api-key: fdsafs


